keys:
  - users:
    - &metamageia age18xnfe59qwzamuk4j0gctp2vj6mu8ypmpq5s05hdqzthxhu0vpscs40aw7u
  - hosts:
    - &desktop age12c8eltd9jyt3c7r2uydesfp07sur6qnpts9cwvfdygaxsdcmq3rs6pznm2
creation_rules:
  - path_regex: "secrets/secrets\\.yaml$"
    key_groups:
    - age:
      - *metamageia
      - *desktop
  - path_regex: "secrets/secrets\\.env$"
    key_groups:
    - age:
      - *metamageia
      - *desktop