apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: jellyfin
spec:
  replicas: 1
  template:
    spec:
      hostNetwork: true
      containers:
      - name: jellyfin
        image: jellyfin/jellyfin
        securityContext:
          privileged: true
        ports:
        - containerPort: 8096
        volumeMounts:
        - name: config
          mountPath: /config
        - name: media
          mountPath: /media
          readOnly: true
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: jellyfin-config
      - name: media
        hostPath:
          path: /media
          type: Directory
      - name: dev-fuse
        hostPath:
          path: /dev/fuse
