apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
- includeSelectors: true
  pairs:
    app: jellyfin

resources:
- deploy.yaml
- namespace.yaml
- pvc.yaml
- service.yaml
- ingress.yaml
- secret.yaml
- storage-class.yaml

