apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f compose.yaml
    kompose.version: 1.36.0 (HEAD)
  labels:
    io.kompose.service: vrising
  name: vrising
spec:
  ports:
    - name: "9876"
      port: 9876
      protocol: UDP
      targetPort: 9876
    - name: "9877"
      port: 9877
      protocol: UDP
      targetPort: 9877
  selector:
    io.kompose.service: vrising
