name: Build NixOS Image for Digital Ocean

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check Flake
      run: nix build .#packages.x86_64-linux.do

    - name: Upload image to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./result/*.gz
        asset_name: nixos.x86_64-linux.do
        tag: ${{ github.ref }}
        overwrite: true
        body: "Updated custom NixOS unstable image for Digital Ocean"

      